# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/apps/software/devel/CMake/3.24.3-GCCcore-11.3.0/bin/cmake

# The command to remove a file.
RM = /opt/apps/software/devel/CMake/3.24.3-GCCcore-11.3.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kazuumi/rsun_koastore/kazuumiTest1/nwchemexTEST1/nwchemex_gcc_gccNWC_automated_noprovisional_try1/VENUSplugin1/venus_nwchemex_plugin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kazuumi/rsun_koastore/kazuumiTest1/nwchemexTEST1/nwchemex_gcc_gccNWC_automated_noprovisional_try1/VENUSplugin1/venus_nwchemex_plugin/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/opt/apps/software/devel/CMake/3.24.3-GCCcore-11.3.0/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/opt/apps/software/devel/CMake/3.24.3-GCCcore-11.3.0/bin/cpack --config ./CPackSourceConfig.cmake /home/kazuumi/rsun_koastore/kazuumiTest1/nwchemexTEST1/nwchemex_gcc_gccNWC_automated_noprovisional_try1/VENUSplugin1/venus_nwchemex_plugin/build/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/opt/apps/software/devel/CMake/3.24.3-GCCcore-11.3.0/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/apps/software/devel/CMake/3.24.3-GCCcore-11.3.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/apps/software/devel/CMake/3.24.3-GCCcore-11.3.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/apps/software/devel/CMake/3.24.3-GCCcore-11.3.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/apps/software/devel/CMake/3.24.3-GCCcore-11.3.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/apps/software/devel/CMake/3.24.3-GCCcore-11.3.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/apps/software/devel/CMake/3.24.3-GCCcore-11.3.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/apps/software/devel/CMake/3.24.3-GCCcore-11.3.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/apps/software/devel/CMake/3.24.3-GCCcore-11.3.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kazuumi/rsun_koastore/kazuumiTest1/nwchemexTEST1/nwchemex_gcc_gccNWC_automated_noprovisional_try1/VENUSplugin1/venus_nwchemex_plugin/build/CMakeFiles /home/kazuumi/rsun_koastore/kazuumiTest1/nwchemexTEST1/nwchemex_gcc_gccNWC_automated_noprovisional_try1/VENUSplugin1/venus_nwchemex_plugin/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kazuumi/rsun_koastore/kazuumiTest1/nwchemexTEST1/nwchemex_gcc_gccNWC_automated_noprovisional_try1/VENUSplugin1/venus_nwchemex_plugin/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/kazuumi/rsun_koastore/kazuumiTest1/nwchemexTEST1/nwchemex_gcc_gccNWC_automated_noprovisional_try1/VENUSplugin1/venus_nwchemex_plugin/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named venus_nwchemex_plugin

# Build rule for target.
venus_nwchemex_plugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 venus_nwchemex_plugin
.PHONY : venus_nwchemex_plugin

# fast build rule for target.
venus_nwchemex_plugin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/venus_nwchemex_plugin.dir/build.make CMakeFiles/venus_nwchemex_plugin.dir/build
.PHONY : venus_nwchemex_plugin/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named test_venus_nwchemex_plugin

# Build rule for target.
test_venus_nwchemex_plugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_venus_nwchemex_plugin
.PHONY : test_venus_nwchemex_plugin

# fast build rule for target.
test_venus_nwchemex_plugin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_venus_nwchemex_plugin.dir/build.make CMakeFiles/test_venus_nwchemex_plugin.dir/build
.PHONY : test_venus_nwchemex_plugin/fast

#=============================================================================
# Target rules for targets named py_simde

# Build rule for target.
py_simde: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 py_simde
.PHONY : py_simde

# fast build rule for target.
py_simde/fast:
	$(MAKE) $(MAKESILENT) -f _deps/simde-build/CMakeFiles/py_simde.dir/build.make _deps/simde-build/CMakeFiles/py_simde.dir/build
.PHONY : py_simde/fast

#=============================================================================
# Target rules for targets named chemist

# Build rule for target.
chemist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chemist
.PHONY : chemist

# fast build rule for target.
chemist/fast:
	$(MAKE) $(MAKESILENT) -f _deps/chemist-build/CMakeFiles/chemist.dir/build.make _deps/chemist-build/CMakeFiles/chemist.dir/build
.PHONY : chemist/fast

#=============================================================================
# Target rules for targets named py_chemist

# Build rule for target.
py_chemist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 py_chemist
.PHONY : py_chemist

# fast build rule for target.
py_chemist/fast:
	$(MAKE) $(MAKESILENT) -f _deps/chemist-build/CMakeFiles/py_chemist.dir/build.make _deps/chemist-build/CMakeFiles/py_chemist.dir/build
.PHONY : py_chemist/fast

#=============================================================================
# Target rules for targets named parallelzone

# Build rule for target.
parallelzone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parallelzone
.PHONY : parallelzone

# fast build rule for target.
parallelzone/fast:
	$(MAKE) $(MAKESILENT) -f _deps/parallelzone-build/CMakeFiles/parallelzone.dir/build.make _deps/parallelzone-build/CMakeFiles/parallelzone.dir/build
.PHONY : parallelzone/fast

#=============================================================================
# Target rules for targets named py_parallelzone

# Build rule for target.
py_parallelzone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 py_parallelzone
.PHONY : py_parallelzone

# fast build rule for target.
py_parallelzone/fast:
	$(MAKE) $(MAKESILENT) -f _deps/parallelzone-build/CMakeFiles/py_parallelzone.dir/build.make _deps/parallelzone-build/CMakeFiles/py_parallelzone.dir/build
.PHONY : py_parallelzone/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) $(MAKESILENT) -f _deps/spdlog-build/CMakeFiles/spdlog.dir/build.make _deps/spdlog-build/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

#=============================================================================
# Target rules for targets named utilities

# Build rule for target.
utilities: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 utilities
.PHONY : utilities

# fast build rule for target.
utilities/fast:
	$(MAKE) $(MAKESILENT) -f _deps/utilities-build/CMakeFiles/utilities.dir/build.make _deps/utilities-build/CMakeFiles/utilities.dir/build
.PHONY : utilities/fast

#=============================================================================
# Target rules for targets named pluginplay

# Build rule for target.
pluginplay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pluginplay
.PHONY : pluginplay

# fast build rule for target.
pluginplay/fast:
	$(MAKE) $(MAKESILENT) -f _deps/pluginplay-build/CMakeFiles/pluginplay.dir/build.make _deps/pluginplay-build/CMakeFiles/pluginplay.dir/build
.PHONY : pluginplay/fast

#=============================================================================
# Target rules for targets named py_pluginplay

# Build rule for target.
py_pluginplay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 py_pluginplay
.PHONY : py_pluginplay

# fast build rule for target.
py_pluginplay/fast:
	$(MAKE) $(MAKESILENT) -f _deps/pluginplay-build/CMakeFiles/py_pluginplay.dir/build.make _deps/pluginplay-build/CMakeFiles/py_pluginplay.dir/build
.PHONY : py_pluginplay/fast

#=============================================================================
# Target rules for targets named headers

# Build rule for target.
headers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 headers
.PHONY : headers

# fast build rule for target.
headers/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libfort-build/CMakeFiles/headers.dir/build.make _deps/libfort-build/CMakeFiles/headers.dir/build
.PHONY : headers/fast

#=============================================================================
# Target rules for targets named fort

# Build rule for target.
fort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fort
.PHONY : fort

# fast build rule for target.
fort/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libfort-build/lib/CMakeFiles/fort.dir/build.make _deps/libfort-build/lib/CMakeFiles/fort.dir/build
.PHONY : fort/fast

src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.o: src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.cpp.o
.PHONY : src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.o

# target to build an object file
src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/venus_nwchemex_plugin.dir/build.make CMakeFiles/venus_nwchemex_plugin.dir/src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.cpp.o
.PHONY : src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.cpp.o

src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.i: src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.cpp.i
.PHONY : src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.i

# target to preprocess a source file
src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/venus_nwchemex_plugin.dir/build.make CMakeFiles/venus_nwchemex_plugin.dir/src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.cpp.i
.PHONY : src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.cpp.i

src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.s: src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.cpp.s
.PHONY : src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.s

# target to generate assembly for a file
src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/venus_nwchemex_plugin.dir/build.make CMakeFiles/venus_nwchemex_plugin.dir/src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.cpp.s
.PHONY : src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.cpp.s

tests/unit_tests/test_load_modules.o: tests/unit_tests/test_load_modules.cpp.o
.PHONY : tests/unit_tests/test_load_modules.o

# target to build an object file
tests/unit_tests/test_load_modules.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_venus_nwchemex_plugin.dir/build.make CMakeFiles/test_venus_nwchemex_plugin.dir/tests/unit_tests/test_load_modules.cpp.o
.PHONY : tests/unit_tests/test_load_modules.cpp.o

tests/unit_tests/test_load_modules.i: tests/unit_tests/test_load_modules.cpp.i
.PHONY : tests/unit_tests/test_load_modules.i

# target to preprocess a source file
tests/unit_tests/test_load_modules.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_venus_nwchemex_plugin.dir/build.make CMakeFiles/test_venus_nwchemex_plugin.dir/tests/unit_tests/test_load_modules.cpp.i
.PHONY : tests/unit_tests/test_load_modules.cpp.i

tests/unit_tests/test_load_modules.s: tests/unit_tests/test_load_modules.cpp.s
.PHONY : tests/unit_tests/test_load_modules.s

# target to generate assembly for a file
tests/unit_tests/test_load_modules.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_venus_nwchemex_plugin.dir/build.make CMakeFiles/test_venus_nwchemex_plugin.dir/tests/unit_tests/test_load_modules.cpp.s
.PHONY : tests/unit_tests/test_load_modules.cpp.s

tests/unit_tests/test_main.o: tests/unit_tests/test_main.cpp.o
.PHONY : tests/unit_tests/test_main.o

# target to build an object file
tests/unit_tests/test_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_venus_nwchemex_plugin.dir/build.make CMakeFiles/test_venus_nwchemex_plugin.dir/tests/unit_tests/test_main.cpp.o
.PHONY : tests/unit_tests/test_main.cpp.o

tests/unit_tests/test_main.i: tests/unit_tests/test_main.cpp.i
.PHONY : tests/unit_tests/test_main.i

# target to preprocess a source file
tests/unit_tests/test_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_venus_nwchemex_plugin.dir/build.make CMakeFiles/test_venus_nwchemex_plugin.dir/tests/unit_tests/test_main.cpp.i
.PHONY : tests/unit_tests/test_main.cpp.i

tests/unit_tests/test_main.s: tests/unit_tests/test_main.cpp.s
.PHONY : tests/unit_tests/test_main.s

# target to generate assembly for a file
tests/unit_tests/test_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_venus_nwchemex_plugin.dir/build.make CMakeFiles/test_venus_nwchemex_plugin.dir/tests/unit_tests/test_main.cpp.s
.PHONY : tests/unit_tests/test_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... headers"
	@echo "... chemist"
	@echo "... fort"
	@echo "... parallelzone"
	@echo "... pluginplay"
	@echo "... py_chemist"
	@echo "... py_parallelzone"
	@echo "... py_pluginplay"
	@echo "... py_simde"
	@echo "... spdlog"
	@echo "... test_venus_nwchemex_plugin"
	@echo "... utilities"
	@echo "... venus_nwchemex_plugin"
	@echo "... src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.o"
	@echo "... src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.i"
	@echo "... src/venus_nwchemex_plugin/venus_nwchemex_plugin_mm.s"
	@echo "... tests/unit_tests/test_load_modules.o"
	@echo "... tests/unit_tests/test_load_modules.i"
	@echo "... tests/unit_tests/test_load_modules.s"
	@echo "... tests/unit_tests/test_main.o"
	@echo "... tests/unit_tests/test_main.i"
	@echo "... tests/unit_tests/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/kazuumi/rsun_koastore/kazuumiTest1/nwchemexTEST1/nwchemex_gcc_gccNWC_automated_noprovisional_try1/VENUSplugin1/venus_nwchemex_plugin/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

