# This file is generated by CMaize.
# 
# NOTE: Any modifications made in this file may be lost the next time
#       CMake is run.

if(TARGET venus_nwchemex_plugin::venus_nwchemex_plugin)
return()
endif()

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

# Create imported target venus_nwchemex_plugin::venus_nwchemex_plugin
add_library(venus_nwchemex_plugin::venus_nwchemex_plugin SHARED IMPORTED)

set_target_properties(venus_nwchemex_plugin::venus_nwchemex_plugin PROPERTIES
INTERFACE_COMPILE_FEATURES "cxx_std_17"
INTERFACE_INCLUDE_DIRECTORIES "${PACKAGE_PREFIX_DIR}/include"
INTERFACE_LINK_LIBRARIES "nwx::simde"
)

set(_CMAIZE_IMPORT_LOCATION "${PACKAGE_PREFIX_DIR}/lib64/venus_nwchemex_plugin/libvenus_nwchemex_plugin.so.0.0.0")
# TODO: Handle different configurations (Release, Debug, etc.)
# Import target "venus_nwchemex_plugin::venus_nwchemex_plugin" for configuration "???"
set_property(TARGET venus_nwchemex_plugin::venus_nwchemex_plugin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(venus_nwchemex_plugin::venus_nwchemex_plugin PROPERTIES
IMPORTED_LOCATION_RELEASE "${_CMAIZE_IMPORT_LOCATION}"
IMPORTED_SONAME_RELEASE "libvenus_nwchemex_plugin.so.0"
)

# Unset variables used
set(PACKAGE_PREFIX_DIR)
set(_CMAIZE_IMPORT_LOCATION)
